# Generated by Django 2.0.2 on 2018-03-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(default='0', max_length=20, null=True)),
                ('comp_name', models.CharField(default='0', max_length=200)),
                ('comp_symbol', models.CharField(default='0', max_length=20, null=True)),
                ('comp_lastTradedTime', models.CharField(default='0', max_length=20, null=True)),
                ('comp_price', models.CharField(default='0', max_length=20, null=True)),
                ('comp_turnover', models.CharField(default='0', max_length=20, null=True)),
                ('comp_sharevolume', models.CharField(default='0', max_length=20, null=True)),
                ('comp_tradevolume', models.CharField(default='0', max_length=20, null=True)),
                ('comp_change', models.CharField(default='0', max_length=20, null=True)),
                ('comp_changePercentage', models.CharField(default='0', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.CharField(default='0', max_length=20)),
                ('news_title', models.CharField(default='0', max_length=200)),
                ('news_url', models.CharField(default='0', max_length=400)),
                ('news_content', models.CharField(default='0', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cse_app.Company')),
            ],
        ),
    ]
